/* 
 * Influx API Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace InfluxDB.Client.Api.Domain
{
    /// <summary>
    ///     LesserThreshold
    /// </summary>
    [DataContract]
    public class LesserThreshold : Threshold, IEquatable<LesserThreshold>
    {
        /// <summary>
        ///     Defines Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            ///     Enum Lesser for value: lesser
            /// </summary>
            [EnumMember(Value = "lesser")] Lesser = 1
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="LesserThreshold" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LesserThreshold()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="LesserThreshold" /> class.
        /// </summary>
        /// <param name="type">type (required).</param>
        /// <param name="value">value (required).</param>
        public LesserThreshold(TypeEnum type = default, float? value = default, CheckStatusLevel? level = default, bool? allValues = default) : base(level, allValues)
        {
            // to ensure "type" is required (not null)
            Type = type;
            // to ensure "value" is required (not null)
            if (value == null)
                throw new InvalidDataException("value is a required property for LesserThreshold and cannot be null");
            Value = value;
        }

        /// <summary>
        ///     Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public TypeEnum Type { get; set; }


        /// <summary>
        ///     Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", EmitDefaultValue = false)]
        public float? Value { get; set; }

        /// <summary>
        ///     Returns true if LesserThreshold instances are equal
        /// </summary>
        /// <param name="input">Instance of LesserThreshold to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LesserThreshold input)
        {
            if (input == null)
                return false;

            return base.Equals(input) &&
                   (
                       Type == input.Type ||
                       Type.Equals(input.Type)
                   ) && base.Equals(input) &&
                   (
                       Value == input.Value ||
                       Value != null &&
                       Value.Equals(input.Value)
                   );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LesserThreshold {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as LesserThreshold);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = base.GetHashCode();
                hashCode = hashCode * 59 + Type.GetHashCode();
                if (Value != null)
                    hashCode = hashCode * 59 + Value.GetHashCode();
                return hashCode;
            }
        }
    }
}